SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store' AND TABLE_NAME = 'books'
ORDER BY ORDINAL_POSITION;


SELECT 
    COLUMN_NAME AS 'Field',
    COLUMN_TYPE AS 'Type',
    IF(IS_NULLABLE = 'YES', 'YES', 'NO') AS 'Null',
    COLUMN_KEY AS 'Key',
    COALESCE(COLUMN_DEFAULT, 'NULL') AS 'Default',
    EXTRA
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'books'
ORDER BY 
    ORDINAL_POSITION;